### ISSUE TITLE
请问export type StoreState = number是什么意思，一时查不到这种写法，谢谢

### ISSUE THREAD

**Issue by AaronConlon** [beichensky/typescript-react-example#1]

**Comment by beichensky** [comment]
你好，type 是一个关键字，相当于创建一个类型别名。类型别名的意思就是说给一种类型创建一个新的名字。比如说：
``` ts
type NumOrStr = number | string;
```
这行代码的意思就是说创建了一个新的类型，这个类型可以是 `number` 或者 `String`。然后这个类型别名就是 `NumOrStr`。

更多的例子可以查看这里：[类型别名](https://ts.xcatliu.com/advanced/type-aliases)。

我这里使用 `export type StoreState = number` 这个语法的原因是为了给 `Store` 创建一个类型，虽然这个类型只是 `number`，但是为了方便使用时的统一，所以用了这种写法。

然后 `export` 关键字是将这个类型导出，让其他的文件可以进行使用。更多关于 typescript 中使用 export 的说明可以查看这里：[模块](https://www.tslang.cn/docs/handbook/modules.html)。

**Comment by AaronConlon** [comment]
@beichensky 谢谢，明白了。
