### ISSUE TITLE
Failed to compile - Type error

### ISSUE THREAD

**Issue by yejiyang** [beichensky/typescript-react-example#2]
Hello, 

Thanks for sharing the codes.

When I run the code `npm run start`, I got the following error, any clue of how to fix it? 

```
Failed to compile
/home/jiyang/code_camp/react_basic/extlibs/typescript-react-example/typescript-react-todos/src/components/footer/index.tsx
(10,10): Type '{ children: string; filter: VisibilityFilters.SHOW_ALL; }' is not assignable to type 'IntrinsicAttributes & Pick<IProps, never> & IProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Pick<IProps, never> & IProps'.
```

Thanks,
Jiyang

**Comment by beichensky** [comment]
Hello, Jiyang! Sorry, there was an error in this code.
Because the FilterLink component doesn't have a children property, but I passed children past, it caused an error. 
The problem has been fixed so far, you can download it again and have a look.

**Comment by yejiyang** [comment]
Hi Beichen, 

Thanks for the fix. 

I am new to react and typescrit. Ask a basic question, you said passed a children property to FilterLink, which one is the children property you passed?

```
<FilterLink filter={VisibilityFilters.SHOW_ALL}>
            All
 </FilterLink>
```

Thanks,
Jiyang

**Comment by yejiyang** [comment]
另外请教一个问题, 本应该留言在你的掘金博客里,但是没有手机号,无法评论. 
https://juejin.im/post/5c81d10b5188257ee7275222#comment

"使用组件声明时的 Component<P, S> 泛型参数声明，来代替 PropTypes进行类型校验"
这句能展开解释一下不?

多谢

**Comment by beichensky** [comment]
First answer the previous question, the children attribute is the content between the tags, just like "All" in the FilterLink tag here.

**Comment by beichensky** [comment]
`使用组件声明时的 Component<P, S> 泛型参数声明，来代替 PropTypes进行类型校验`，这句话的意思是：
- 之前仅使用 `js` 进行 `react` 编写时，为了对组件属性进行校验，以便在编写代码时就能发现并提示错误，会使用 `prop-types` 插件，使用方式如下：
``` js
import React from 'react';
import PropTypes from 'prop-types';
 
class MyComponent extends React.Component {
  render() {
    // ... do things with the props
  }
}
 
MyComponent.propTypes = {
  // You can declare that a prop is a specific JS primitive. By default, these
  // are all optional.
  optionalArray: PropTypes.array,
  optionalBool: PropTypes.bool,
  optionalFunc: PropTypes.func,
  optionalNumber: PropTypes.number,
  optionalObject: PropTypes.object,
  optionalString: PropTypes.string
}
```
  > 更多 `prop-types` 用法查看[这里](https://www.npmjs.com/package/prop-types)。

- 而使用 `typescript` 编写 `react` 组件，可以直接使用 `typescript` 的接口与泛型进行组件属性的校验，使用方式如下：
``` typescript
import React from 'react';

interface IProps {
  optionalArray: any[];
  optionalBool: boolean;
  optionalFunc: () => void;
  optionalNumber: number;
  optionalObject: object;
  optionalString: string;
}
 
class MyComponent extends React.Component<IProps, any> {
  render() {
    // ... do things with the props
  }
}
```
 这种使用泛型的方式可以用来代替 `PropTypes` 进行组件属性的类型校验。
  > 更多使用 `typescript` 进行类型约束的讲解可以查看[这里](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet)。

**Comment by yejiyang** [comment]
非常感谢, 耐心细致讲解!
